Repository etournity/etournity, pull requests merged in 2023-04, with the labels that each got.

#34 fix(Discovery): Tournaments Query fails when not logged in
  packages/client/pages/tournaments/index.tsx
  packages/server/src/api/tournament/tournament.type.ts
Labels: bug, area:tournament_discovery

#31 chore: reduce focus on game-support in ideas template
  .github/DISCUSSION_TEMPLATE/ideas.yml
Labels: infrastructure

#35 docs: Change incorrect repo url in docs
  README.md
Labels: documentation

#38 fix(Discovery): Fix Tournament Creation Fab position (mobile)
  package.json
  packages/client/components/ui/card/index.tsx
  packages/client/components/ui/tooltip/index.tsx
  packages/client/middleware.ts
  packages/client/package.json
  packages/client/pages/_app.tsx
  packages/client/pages/tournaments/index.module.scss
  yarn.lock
Labels: bug

#41 fix: Tinycolor build failure
  package.json
  packages/client/package.json
  packages/rbac/tsconfig.json
  packages/server/package.json
  packages/server/src/logger.ts
  packages/server/tsconfig.json
  packages/shared/tsconfig.json
  yarn.lock
Labels: bug
