Repository etournity/etournity, pull requests merged in 2023-03, with the labels that each got.

#7 chore(docs): improve templates for PRs and issues
  docs/issue_template.md
  docs/pull_request_template.md
Labels: documentation

#10 chore: Replace Template with Issue Form Template
  docs/issue_template.md
  docs/issue_template/bug_report.yml
  docs/issue_template/config.yml
  docs/pull_request_template.md
Labels: infrastructure

#12 chore: Customize GitHub templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: documentation

#14 fix: missing yarn files
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-berry.cjs
  .yarnrc.yml
  package.json
  packages/server/package.json
  packages/server/src/generated/nexus.d.ts
  packages/server/src/generated/schema.graphql
  yarn.lock
Labels: bug

#8 infra: add deployment workflows
  .github/workflows/ci.yaml
  .github/workflows/dev-backend.yaml
  .github/workflows/dev-frontend.yaml
  .github/workflows/prod-backend.yaml
  .github/workflows/prod-frontend.yaml
  .github/workflows/zap-scan.yaml
Labels: infrastructure

#22 infra: Fix repository url in main package.json
  CHANGELOG.md
  package.json
Labels: infrastructure

#21 docs: Fix typo in and resolution of github banner
  docs/GitHub-Banner.png
Labels: documentation

#15 chore: Fix Typos in README.md
  README.md
Labels: documentation

#25 infra: Switch to lerna-lite and add custom commit types
  .github/pull_request_template.md
  changelogPreset.config.js
  lerna.json
  package.json
  yarn.lock
Labels: infrastructure

#27 chore: add templates for ideas and game support discussions
  .github/DISCUSSION_TEMPLATE/game-support.yml
  .github/DISCUSSION_TEMPLATE/ideas.yml
Labels: documentation
